<?php
/**
 * Implements hook_menu()
 **/
function lopu_menu() {
	// Url or menu of page that provide login form to call by a link 
	$items['lopu/%ctools_js/login'] = array(
		'title' => t('User Login'),
		'page arguments' => array(1),
		'page callback' => 'ctools_modal_page',
		'access callback' => TRUE,
		'file' => 'lopu.pages.inc',
		'type' => MENU_CALLBACK,
	);

	// url  or menu of page that provide a link to call page above (OPTIONAL)
	$items['ctools_ajax_sample'] = array(
		//'title' => 'Ctools Login Modal',
		'page callback' => 'ctools_ajax_sample_page',
		'access callback' => TRUE,
		'file' => 'lopu.pages.inc',
		'type' => MENU_CALLBACK,
	);

	$items['lopu/%ctools_js/dismiss'] = array(
		'title' => 'Dismiss',
		'page callback' => 'lopu_dismiss',
		'page arguments' => array(1),
		'access callback' => TRUE,
		'file' => 'lopu.pages.inc',
		'type' => MENU_CALLBACK,
	);
	return $items;
}

/**
 * Implements hook_form_FORM_ID_alter()
 */
function lopu_form_user_login_alter(&$form, &$form_state, $form_id) {
	if (arg(0) == 'lopu') {
		$form['#prefix'] = '<div id="lopu-login" class="lopu-login-wrapper">';
		$form['#prefix'] .=	'<div class="user-login-block">';
		$form['#prefix'] .= '<div class="lopu-title user-login-title"><div class="text">' . t('Log in to your account.') . '</div></div>';
		unset($form['name']['#title']);	
		$form['name']['#attributes']['placeholder'] = t( 'Username' );
		unset($form['name']['#description']);
		unset($form['pass']['#title']);
		$form['pass']['#attributes']['placeholder'] = t( 'Password' );
		unset($form['pass']['#description']);
		$form['links'] = array('#markup' => l(t('Forgotten your password?'), 'user/password', array('attributes' => array('title' => t('Request new password.')))));
		$form['#suffix'] = '</div>';
		$form['#suffix'] .= '<div class="user-register-block">';
		$form['#suffix'] .= '<div class="lopu-title user-register-title"><div class="text">' . t('Not yet a member?') . '</div></div>';
		$form['#suffix'] .= '<div class="register-description"><span>' . t('Register for an account to access content.') . '</span></div>';
		$form['#suffix'] .= '<div class="register-link">' . l(t('Register now.'), 'user/register', array('attributes' => array('title' => t('User register.')))) . '</div>';
		$form['#suffix'] .= '</div>';
		$form['#suffix'] .= '</div>';
		/*
		$items[] = l(t('Créer un nouveau compte'), 'user/register', array('attributes' => array('title' => t('Créer un nouveau compte.'))));
		$items[] = l(t('Request new password'), 'user/password', array('attributes' => array('title' => t('Request new password via e-mail.'))));
		$form['links'] = array('#markup' => theme('item_list', array('items' => $items)));
		*/
	}
}

/**
 * Implements hook_preprocess_html()
 * Provide ctools js to all pages
 **/
function lopu_preprocess_html(&$variables) {
	static $already_added = FALSE;
	if ($already_added) {
	  return; // Don't add the JavaScript and CSS multiple times.
	}
	ctools_include('ajax');
	ctools_include('modal');
	ctools_modal_add_js();

	$js_settings = array(
		'custom' => array(
			'modalSize' => array(
			  'type' => 'fixed',
			  'width' => floatval(700),
			  'height' => floatval(250),
			),
			'modalOptions' => array(
			  'opacity' => floatval(0.85),
			  'background' => '#000',
			),
			'animation' => 'fadeIn',
			'modalTheme' => 'LopuPopup',
			//'throbber' => $throbber,
			'closeText' => t('Close'),
		),
	);
	drupal_add_js($js_settings, 'setting');
	
	// Add modal_forms own js and CSS.
	ctools_add_css('lopu_popup', 'lopu');
	ctools_add_js('lopu_popup', 'lopu');

	$already_added = TRUE;
}
